# docker-compose.yml
services:
  nifi:
    image: apache/nifi:latest
    ports:
      - "8080:8080"
    environment:
      - NIFI_WEB_HTTP_PORT=8080
    volumes:
      - ./nifi/templates:/opt/nifi/nifi-current/templates

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  api:
    build: ./api
    depends_on:
      - qdrant
    ports:
      - "8000:8000"
    environment:
      - QDRANT_URL=http://qdrant:6333
      - EMBEDDING_MODEL=BAAI/bge-small-en-v1.5

volumes:
  qdrant_data:
