# docker-compose.yml
services:
  nifi:
    image: apache/nifi:2.6.0
    ports: ["8443:8443"]
    environment:
      - NIFI_WEB_HTTPS_PORT=8443
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD=adminadminadmin
    volumes:
      - nifi_state:/opt/nifi/nifi-current
      - ./nifi/templates:/opt/nifi/nifi-current/templates

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  api:
    build: ./api
    depends_on:
      - qdrant
    ports:
      - "8000:8000"
    environment:
      - QDRANT_URL=http://qdrant:6333
      - EMBEDDING_MODEL=BAAI/bge-small-en-v1.5

volumes:
  nifi_state:
  qdrant_data:
